### ISSUE TITLE
Improve mobile UX

### ISSUE THREAD

**Issue by nuke-web3** [Cryptorado-Community/Cryptorado-Community.github.io#1]
- [x] Buttons rendering correctly in shape & location & size
- [x] More uniform text size
- [x] All elements displayed on calendar (cuts off agenda view tab & further stuff to the right)
- [ ] ... more?

**Comment by rmn5124** [comment]
Hey, can I work on this issue?

**Comment by nuke-web3** [comment]
Sure @rmn5124! I would love some design and implementation help. Happy to review a PR or collaborate one :)
