### ISSUE TITLE
Feat: banner image to change reactively

### ISSUE THREAD

**Issue by nuke-web3** [Cryptorado-Community/Cryptorado-Community.github.io#3]
bring back https://github.com/Cryptorado-Community/Cryptorado-HTML/blob/b4c760d680f18e8f63fdd2f3fded3066a46e09d8/site/images/cryptorado_banner.png

But use the smaller logo for mobile with css?
https://github.com/Cryptorado-Community/Cryptorado-HTML/blob/main/site/assets/main.css#L532
```css
@media screen and (max-width: 980px) {...}
```

**Comment by ghost** [comment]
Hey ^^ I don't know if I understood correctly, but what you want to do is to use the large banner from a certain screen width, and on smaller devices use the one that is currently on the page?

**Comment by ghost** [comment]
I approached this issue here #7

**Comment by nuke-web3** [comment]
`vh` used instead
